# Generated by Django 3.0.8 on 2020-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_floder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=256)),
                ('folder_name', models.CharField(max_length=256)),
                ('uploader', models.CharField(max_length=128)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Floder',
            new_name='Folder',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='floder_name',
            new_name='folder_name',
        ),
    ]
